# Generated by Django 2.2.6 on 2019-10-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystorage', '0002_album_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='weather',
            field=models.CharField(default='Sunny', max_length=10),
        ),
        migrations.AddField(
            model_name='essay',
            name='weather',
            field=models.CharField(default='Sunny', max_length=10),
        ),
        migrations.AddField(
            model_name='files',
            name='weather',
            field=models.CharField(default='Sunny', max_length=10),
        ),
    ]
